/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBentoBoxV1__factory } from "./IBentoBoxV1__factory";
export { IFlashBorrower__factory } from "./IFlashBorrower__factory";
