mainnet:
  chain_id: 1
  hash_tag_prefix: ''
  main_symbol: 'ETH'
  usdp_symbol: 'USDP'
  uniswap_factory: '0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f'
  sushiswap_factory: '0xC0AEe478e3658e2610c5F7A4A2E1777cE9e4f2Ac'
  sushiswap_init_code_hash: '0xe18a34eb0e04b04f7a0ac29a6e80748dca96319b42c54d679cb821dca90c6303'
  weth: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
  router_check_timeout: 10
  router_confirmations_threshold: 3
  router_harvest_threshold: 200
  router_harvest_threshold_worker: 400