/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface OpenMevRouterTestInterface extends utils.Interface {
  functions: {
    "IS_TEST()": FunctionFragment;
    "failed()": FunctionFragment;
    "setUp()": FunctionFragment;
    "testAddLiquidityExpired()": FunctionFragment;
    "testAddLiquidityInsufficientAmountA()": FunctionFragment;
    "testAddLiquidityInsufficientAmountB()": FunctionFragment;
    "testAllPairs()": FunctionFragment;
    "testLiquidityEth()": FunctionFragment;
    "testLiquidityEthSupportingFeeOnTransfer()": FunctionFragment;
    "testLiquidityTokens()": FunctionFragment;
    "testSwapETHForExactTokens()": FunctionFragment;
    "testSwapExactETHForTokens()": FunctionFragment;
    "testSwapExactETHForTokensBackrun()": FunctionFragment;
    "testSwapExactETHForTokensSupportingFeeOnTransferTokens()": FunctionFragment;
    "testSwapExactTokensForETH()": FunctionFragment;
    "testSwapExactTokensForETHSupportingFeeOnTransferTokens()": FunctionFragment;
    "testSwapExactTokensForTokens()": FunctionFragment;
    "testSwapExactTokensForTokensSupportingFeeOnTransferTokens()": FunctionFragment;
    "testSwapExpired()": FunctionFragment;
    "testSwapIdenticalAddresses()": FunctionFragment;
    "testSwapInsufficientOutputAmount()": FunctionFragment;
    "testSwapInvalidPath()": FunctionFragment;
    "testSwapTokensForExactETH()": FunctionFragment;
    "testSwapTokensForExactTokens()": FunctionFragment;
    "testSwapZeroAddress()": FunctionFragment;
    "testSwapZeroAmount()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "IS_TEST"
      | "failed"
      | "setUp"
      | "testAddLiquidityExpired"
      | "testAddLiquidityInsufficientAmountA"
      | "testAddLiquidityInsufficientAmountB"
      | "testAllPairs"
      | "testLiquidityEth"
      | "testLiquidityEthSupportingFeeOnTransfer"
      | "testLiquidityTokens"
      | "testSwapETHForExactTokens"
      | "testSwapExactETHForTokens"
      | "testSwapExactETHForTokensBackrun"
      | "testSwapExactETHForTokensSupportingFeeOnTransferTokens"
      | "testSwapExactTokensForETH"
      | "testSwapExactTokensForETHSupportingFeeOnTransferTokens"
      | "testSwapExactTokensForTokens"
      | "testSwapExactTokensForTokensSupportingFeeOnTransferTokens"
      | "testSwapExpired"
      | "testSwapIdenticalAddresses"
      | "testSwapInsufficientOutputAmount"
      | "testSwapInvalidPath"
      | "testSwapTokensForExactETH"
      | "testSwapTokensForExactTokens"
      | "testSwapZeroAddress"
      | "testSwapZeroAmount"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "IS_TEST", values?: undefined): string;
  encodeFunctionData(functionFragment: "failed", values?: undefined): string;
  encodeFunctionData(functionFragment: "setUp", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "testAddLiquidityExpired",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testAddLiquidityInsufficientAmountA",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testAddLiquidityInsufficientAmountB",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testAllPairs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testLiquidityEth",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testLiquidityEthSupportingFeeOnTransfer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testLiquidityTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testSwapETHForExactTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testSwapExactETHForTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testSwapExactETHForTokensBackrun",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testSwapExactETHForTokensSupportingFeeOnTransferTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testSwapExactTokensForETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testSwapExactTokensForETHSupportingFeeOnTransferTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testSwapExactTokensForTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testSwapExactTokensForTokensSupportingFeeOnTransferTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testSwapExpired",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testSwapIdenticalAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testSwapInsufficientOutputAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testSwapInvalidPath",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testSwapTokensForExactETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testSwapTokensForExactTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testSwapZeroAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testSwapZeroAmount",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "IS_TEST", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "failed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setUp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "testAddLiquidityExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testAddLiquidityInsufficientAmountA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testAddLiquidityInsufficientAmountB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testAllPairs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testLiquidityEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testLiquidityEthSupportingFeeOnTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testLiquidityTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testSwapETHForExactTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testSwapExactETHForTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testSwapExactETHForTokensBackrun",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testSwapExactETHForTokensSupportingFeeOnTransferTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testSwapExactTokensForETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testSwapExactTokensForETHSupportingFeeOnTransferTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testSwapExactTokensForTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testSwapExactTokensForTokensSupportingFeeOnTransferTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testSwapExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testSwapIdenticalAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testSwapInsufficientOutputAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testSwapInvalidPath",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testSwapTokensForExactETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testSwapTokensForExactTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testSwapZeroAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testSwapZeroAmount",
    data: BytesLike
  ): Result;

  events: {
    "log(string)": EventFragment;
    "log_address(address)": EventFragment;
    "log_bytes(bytes)": EventFragment;
    "log_bytes32(bytes32)": EventFragment;
    "log_int(int256)": EventFragment;
    "log_named_address(string,address)": EventFragment;
    "log_named_bool(string,bool)": EventFragment;
    "log_named_bytes(string,bytes)": EventFragment;
    "log_named_bytes32(string,bytes32)": EventFragment;
    "log_named_decimal_int(string,int256,uint256)": EventFragment;
    "log_named_decimal_uint(string,uint256,uint256)": EventFragment;
    "log_named_int(string,int256)": EventFragment;
    "log_named_string(string,string)": EventFragment;
    "log_named_uint(string,uint256)": EventFragment;
    "log_string(string)": EventFragment;
    "log_uint(uint256)": EventFragment;
    "logs(bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "log"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_address"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_bytes"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_bytes32"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_int"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_address"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_bool"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_bytes"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_bytes32"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_decimal_int"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_decimal_uint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_int"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_string"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_uint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_string"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_uint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "logs"): EventFragment;
}

export interface logEventObject {
  arg0: string;
}
export type logEvent = TypedEvent<[string], logEventObject>;

export type logEventFilter = TypedEventFilter<logEvent>;

export interface log_addressEventObject {
  arg0: string;
}
export type log_addressEvent = TypedEvent<[string], log_addressEventObject>;

export type log_addressEventFilter = TypedEventFilter<log_addressEvent>;

export interface log_bytesEventObject {
  arg0: string;
}
export type log_bytesEvent = TypedEvent<[string], log_bytesEventObject>;

export type log_bytesEventFilter = TypedEventFilter<log_bytesEvent>;

export interface log_bytes32EventObject {
  arg0: string;
}
export type log_bytes32Event = TypedEvent<[string], log_bytes32EventObject>;

export type log_bytes32EventFilter = TypedEventFilter<log_bytes32Event>;

export interface log_intEventObject {
  arg0: BigNumber;
}
export type log_intEvent = TypedEvent<[BigNumber], log_intEventObject>;

export type log_intEventFilter = TypedEventFilter<log_intEvent>;

export interface log_named_addressEventObject {
  key: string;
  val: string;
}
export type log_named_addressEvent = TypedEvent<
  [string, string],
  log_named_addressEventObject
>;

export type log_named_addressEventFilter =
  TypedEventFilter<log_named_addressEvent>;

export interface log_named_boolEventObject {
  key: string;
  val: boolean;
}
export type log_named_boolEvent = TypedEvent<
  [string, boolean],
  log_named_boolEventObject
>;

export type log_named_boolEventFilter = TypedEventFilter<log_named_boolEvent>;

export interface log_named_bytesEventObject {
  key: string;
  val: string;
}
export type log_named_bytesEvent = TypedEvent<
  [string, string],
  log_named_bytesEventObject
>;

export type log_named_bytesEventFilter = TypedEventFilter<log_named_bytesEvent>;

export interface log_named_bytes32EventObject {
  key: string;
  val: string;
}
export type log_named_bytes32Event = TypedEvent<
  [string, string],
  log_named_bytes32EventObject
>;

export type log_named_bytes32EventFilter =
  TypedEventFilter<log_named_bytes32Event>;

export interface log_named_decimal_intEventObject {
  key: string;
  val: BigNumber;
  decimals: BigNumber;
}
export type log_named_decimal_intEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  log_named_decimal_intEventObject
>;

export type log_named_decimal_intEventFilter =
  TypedEventFilter<log_named_decimal_intEvent>;

export interface log_named_decimal_uintEventObject {
  key: string;
  val: BigNumber;
  decimals: BigNumber;
}
export type log_named_decimal_uintEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  log_named_decimal_uintEventObject
>;

export type log_named_decimal_uintEventFilter =
  TypedEventFilter<log_named_decimal_uintEvent>;

export interface log_named_intEventObject {
  key: string;
  val: BigNumber;
}
export type log_named_intEvent = TypedEvent<
  [string, BigNumber],
  log_named_intEventObject
>;

export type log_named_intEventFilter = TypedEventFilter<log_named_intEvent>;

export interface log_named_stringEventObject {
  key: string;
  val: string;
}
export type log_named_stringEvent = TypedEvent<
  [string, string],
  log_named_stringEventObject
>;

export type log_named_stringEventFilter =
  TypedEventFilter<log_named_stringEvent>;

export interface log_named_uintEventObject {
  key: string;
  val: BigNumber;
}
export type log_named_uintEvent = TypedEvent<
  [string, BigNumber],
  log_named_uintEventObject
>;

export type log_named_uintEventFilter = TypedEventFilter<log_named_uintEvent>;

export interface log_stringEventObject {
  arg0: string;
}
export type log_stringEvent = TypedEvent<[string], log_stringEventObject>;

export type log_stringEventFilter = TypedEventFilter<log_stringEvent>;

export interface log_uintEventObject {
  arg0: BigNumber;
}
export type log_uintEvent = TypedEvent<[BigNumber], log_uintEventObject>;

export type log_uintEventFilter = TypedEventFilter<log_uintEvent>;

export interface logsEventObject {
  arg0: string;
}
export type logsEvent = TypedEvent<[string], logsEventObject>;

export type logsEventFilter = TypedEventFilter<logsEvent>;

export interface OpenMevRouterTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OpenMevRouterTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    IS_TEST(overrides?: CallOverrides): Promise<[boolean]>;

    failed(overrides?: CallOverrides): Promise<[boolean]>;

    setUp(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testAddLiquidityExpired(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testAddLiquidityInsufficientAmountA(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testAddLiquidityInsufficientAmountB(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testAllPairs(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testLiquidityEth(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testLiquidityEthSupportingFeeOnTransfer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testLiquidityTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testSwapETHForExactTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testSwapExactETHForTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testSwapExactETHForTokensBackrun(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testSwapExactETHForTokensSupportingFeeOnTransferTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testSwapExactTokensForETH(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testSwapExactTokensForETHSupportingFeeOnTransferTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testSwapExactTokensForTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testSwapExactTokensForTokensSupportingFeeOnTransferTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testSwapExpired(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testSwapIdenticalAddresses(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testSwapInsufficientOutputAmount(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testSwapInvalidPath(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testSwapTokensForExactETH(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testSwapTokensForExactTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testSwapZeroAddress(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testSwapZeroAmount(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  IS_TEST(overrides?: CallOverrides): Promise<boolean>;

  failed(overrides?: CallOverrides): Promise<boolean>;

  setUp(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testAddLiquidityExpired(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testAddLiquidityInsufficientAmountA(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testAddLiquidityInsufficientAmountB(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testAllPairs(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testLiquidityEth(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testLiquidityEthSupportingFeeOnTransfer(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testLiquidityTokens(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testSwapETHForExactTokens(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testSwapExactETHForTokens(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testSwapExactETHForTokensBackrun(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testSwapExactETHForTokensSupportingFeeOnTransferTokens(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testSwapExactTokensForETH(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testSwapExactTokensForETHSupportingFeeOnTransferTokens(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testSwapExactTokensForTokens(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testSwapExactTokensForTokensSupportingFeeOnTransferTokens(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testSwapExpired(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testSwapIdenticalAddresses(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testSwapInsufficientOutputAmount(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testSwapInvalidPath(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testSwapTokensForExactETH(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testSwapTokensForExactTokens(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testSwapZeroAddress(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testSwapZeroAmount(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    IS_TEST(overrides?: CallOverrides): Promise<boolean>;

    failed(overrides?: CallOverrides): Promise<boolean>;

    setUp(overrides?: CallOverrides): Promise<void>;

    testAddLiquidityExpired(overrides?: CallOverrides): Promise<void>;

    testAddLiquidityInsufficientAmountA(
      overrides?: CallOverrides
    ): Promise<void>;

    testAddLiquidityInsufficientAmountB(
      overrides?: CallOverrides
    ): Promise<void>;

    testAllPairs(overrides?: CallOverrides): Promise<void>;

    testLiquidityEth(overrides?: CallOverrides): Promise<void>;

    testLiquidityEthSupportingFeeOnTransfer(
      overrides?: CallOverrides
    ): Promise<void>;

    testLiquidityTokens(overrides?: CallOverrides): Promise<void>;

    testSwapETHForExactTokens(overrides?: CallOverrides): Promise<void>;

    testSwapExactETHForTokens(overrides?: CallOverrides): Promise<void>;

    testSwapExactETHForTokensBackrun(overrides?: CallOverrides): Promise<void>;

    testSwapExactETHForTokensSupportingFeeOnTransferTokens(
      overrides?: CallOverrides
    ): Promise<void>;

    testSwapExactTokensForETH(overrides?: CallOverrides): Promise<void>;

    testSwapExactTokensForETHSupportingFeeOnTransferTokens(
      overrides?: CallOverrides
    ): Promise<void>;

    testSwapExactTokensForTokens(overrides?: CallOverrides): Promise<void>;

    testSwapExactTokensForTokensSupportingFeeOnTransferTokens(
      overrides?: CallOverrides
    ): Promise<void>;

    testSwapExpired(overrides?: CallOverrides): Promise<void>;

    testSwapIdenticalAddresses(overrides?: CallOverrides): Promise<void>;

    testSwapInsufficientOutputAmount(overrides?: CallOverrides): Promise<void>;

    testSwapInvalidPath(overrides?: CallOverrides): Promise<void>;

    testSwapTokensForExactETH(overrides?: CallOverrides): Promise<void>;

    testSwapTokensForExactTokens(overrides?: CallOverrides): Promise<void>;

    testSwapZeroAddress(overrides?: CallOverrides): Promise<void>;

    testSwapZeroAmount(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "log(string)"(arg0?: null): logEventFilter;
    log(arg0?: null): logEventFilter;

    "log_address(address)"(arg0?: null): log_addressEventFilter;
    log_address(arg0?: null): log_addressEventFilter;

    "log_bytes(bytes)"(arg0?: null): log_bytesEventFilter;
    log_bytes(arg0?: null): log_bytesEventFilter;

    "log_bytes32(bytes32)"(arg0?: null): log_bytes32EventFilter;
    log_bytes32(arg0?: null): log_bytes32EventFilter;

    "log_int(int256)"(arg0?: null): log_intEventFilter;
    log_int(arg0?: null): log_intEventFilter;

    "log_named_address(string,address)"(
      key?: null,
      val?: null
    ): log_named_addressEventFilter;
    log_named_address(key?: null, val?: null): log_named_addressEventFilter;

    "log_named_bool(string,bool)"(
      key?: null,
      val?: null
    ): log_named_boolEventFilter;
    log_named_bool(key?: null, val?: null): log_named_boolEventFilter;

    "log_named_bytes(string,bytes)"(
      key?: null,
      val?: null
    ): log_named_bytesEventFilter;
    log_named_bytes(key?: null, val?: null): log_named_bytesEventFilter;

    "log_named_bytes32(string,bytes32)"(
      key?: null,
      val?: null
    ): log_named_bytes32EventFilter;
    log_named_bytes32(key?: null, val?: null): log_named_bytes32EventFilter;

    "log_named_decimal_int(string,int256,uint256)"(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_intEventFilter;
    log_named_decimal_int(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_intEventFilter;

    "log_named_decimal_uint(string,uint256,uint256)"(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_uintEventFilter;
    log_named_decimal_uint(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_uintEventFilter;

    "log_named_int(string,int256)"(
      key?: null,
      val?: null
    ): log_named_intEventFilter;
    log_named_int(key?: null, val?: null): log_named_intEventFilter;

    "log_named_string(string,string)"(
      key?: null,
      val?: null
    ): log_named_stringEventFilter;
    log_named_string(key?: null, val?: null): log_named_stringEventFilter;

    "log_named_uint(string,uint256)"(
      key?: null,
      val?: null
    ): log_named_uintEventFilter;
    log_named_uint(key?: null, val?: null): log_named_uintEventFilter;

    "log_string(string)"(arg0?: null): log_stringEventFilter;
    log_string(arg0?: null): log_stringEventFilter;

    "log_uint(uint256)"(arg0?: null): log_uintEventFilter;
    log_uint(arg0?: null): log_uintEventFilter;

    "logs(bytes)"(arg0?: null): logsEventFilter;
    logs(arg0?: null): logsEventFilter;
  };

  estimateGas: {
    IS_TEST(overrides?: CallOverrides): Promise<BigNumber>;

    failed(overrides?: CallOverrides): Promise<BigNumber>;

    setUp(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testAddLiquidityExpired(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testAddLiquidityInsufficientAmountA(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testAddLiquidityInsufficientAmountB(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testAllPairs(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testLiquidityEth(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testLiquidityEthSupportingFeeOnTransfer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testLiquidityTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testSwapETHForExactTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testSwapExactETHForTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testSwapExactETHForTokensBackrun(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testSwapExactETHForTokensSupportingFeeOnTransferTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testSwapExactTokensForETH(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testSwapExactTokensForETHSupportingFeeOnTransferTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testSwapExactTokensForTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testSwapExactTokensForTokensSupportingFeeOnTransferTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testSwapExpired(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testSwapIdenticalAddresses(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testSwapInsufficientOutputAmount(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testSwapInvalidPath(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testSwapTokensForExactETH(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testSwapTokensForExactTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testSwapZeroAddress(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testSwapZeroAmount(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    IS_TEST(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    failed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setUp(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testAddLiquidityExpired(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testAddLiquidityInsufficientAmountA(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testAddLiquidityInsufficientAmountB(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testAllPairs(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testLiquidityEth(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testLiquidityEthSupportingFeeOnTransfer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testLiquidityTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testSwapETHForExactTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testSwapExactETHForTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testSwapExactETHForTokensBackrun(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testSwapExactETHForTokensSupportingFeeOnTransferTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testSwapExactTokensForETH(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testSwapExactTokensForETHSupportingFeeOnTransferTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testSwapExactTokensForTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testSwapExactTokensForTokensSupportingFeeOnTransferTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testSwapExpired(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testSwapIdenticalAddresses(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testSwapInsufficientOutputAmount(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testSwapInvalidPath(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testSwapTokensForExactETH(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testSwapTokensForExactTokens(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testSwapZeroAddress(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testSwapZeroAmount(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
