/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IProtocolDataProvider,
  IProtocolDataProviderInterface,
} from "../../../contracts/SushiGuardV01.sol/IProtocolDataProvider";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getReserveData",
    outputs: [
      {
        internalType: "uint256",
        name: "availableLiquidity",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IProtocolDataProvider__factory {
  static readonly abi = _abi;
  static createInterface(): IProtocolDataProviderInterface {
    return new utils.Interface(_abi) as IProtocolDataProviderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IProtocolDataProvider {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IProtocolDataProvider;
  }
}
