/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iBentoBoxSol from "./IBentoBox.sol";
export type { iBentoBoxSol };
import type * as iUniswapV2RouterSol from "./IUniswapV2Router.sol";
export type { iUniswapV2RouterSol };
export type { ILendingPool } from "./ILendingPool";
export type { IOpenMevRouter } from "./IOpenMevRouter";
export type { IProtocolDataProvider } from "./IProtocolDataProvider";
export type { IUniswapV2Factory } from "./IUniswapV2Factory";
export type { IUniswapV2Pair } from "./IUniswapV2Pair";
export type { IWETH } from "./IWETH";
