/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openMevRouterTSol from "./OpenMevRouter.t.sol";
export type { openMevRouterTSol };
import type * as openMevRouterFuzzTSol from "./OpenMevRouterFuzz.t.sol";
export type { openMevRouterFuzzTSol };
import type * as openMevZapperTSol from "./OpenMevZapper.t.sol";
export type { openMevZapperTSol };
import type * as revertingErc20TSol from "./RevertingERC20.t.sol";
export type { revertingErc20TSol };
import type * as uint512TSol from "./Uint512.t.sol";
export type { uint512TSol };
import type * as dsTestSol from "./ds-test.sol";
export type { dsTestSol };
